# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: CD-Tasts.Api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read 

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET 
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          
      - name: Restore
        run: dotnet restore src/Tasks.Api/Tasks.Api.csproj
      - name: Build
        run: dotnet build src/Tasks.Api/Tasks.Api.csproj --configuration Release --no-restore

      - name: Test
        run: dotnet test src/Tasks.Api.Tests/Tasks.Api.Tests.csproj --configuration Release 

      - name: Publish
        run: dotnet publish src/Tasks.Api/Tasks.Api.csproj --configuration Release --no-build -o "${{ env.DOTNET_ROOT }}/myapp"     

      - name: Upload artifact 
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: publish
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C57CA65B44134262B30A535474B36364 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B717212DE1CA49429105864D020EC7B6 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3D9F528A20244B9CBE6A14125722CCBF }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'app-tntu-tasks-api'
          slot-name: 'Production'
          package: publish
          
